import Head from 'next/head'
import { MdDarkMode} from 'react-icons/md';
import { CgSun } from 'react-icons/cg';
import {GiHamburgerMenu} from 'react-icons/gi'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kryselle Matienzo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-[rgb(254, 250, 246)] px-10">
        <section className="min-h-screen">
          <nav className="flex justify-between py-10 items-center">
            <h1 className="text-xl font-semibold whitespace-nowrap dark:text-white">Kryselle Matienzo</h1>
            {/* Hamburger menu shows when screen size is 767px and below */}
            <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <GiHamburgerMenu aria-hidden="true"></GiHamburgerMenu>
            </button>
              
    

            <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul className="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
              {/* <ul className="flex items-center flex-row"> */}
              <li>Home</li>
              <li>Work</li>
              <li>About</li>
              <li>Contact</li>
              <li><MdDarkMode></MdDarkMode><CgSun></CgSun></li>
              
            </ul>
            </div>
            
          </nav>
        </section>

      </main>
    </div>
  )
}
